Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -56,25 +56,19 @@ jobs:
           echo "Attempt to whitelist IP..."
           curl -sX POST -d 'whitelist[address]=${{ steps.ip.outputs.ipv4 }}' -d 'whitelist[port]=22' "https://${{ secrets.REMOTE_USER }}:${{ secrets.URL_ENCODED_PASSWORD }}@${{ secrets.REMOTE_HOST }}:2083/$ENDPOINT?r=add" | jq
 
-      # Déployer la branche 'dev' sur le préprod
-        #      - name: Deploy on develop branch
-        #if: ${{ github.ref == 'refs/heads/develop' }}
-        #uses: easingthemes/ssh-deploy@main
-          #with:
-          #SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
-          #ARGS: "-rlgoDzvc -i --delete-after"
-          #SOURCE: "./"
-          #REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
-          #REMOTE_USER: ${{ secrets.REMOTE_USER }}
-          #TARGET: ${{ secrets.REMOTE_PREPROD_TARGET }}
-          #EXCLUDE: "/dist/, /node_modules/"
-          #SCRIPT_BEFORE: |
-          # whoami
-          # ls -al
-          #SCRIPT_AFTER: |
-          # whoami
-          #  ls -al
-        #  echo $RSYNC_STDOUT
+      # Ajouter la clé privée SSH (convertie en PEM)
+      - name: Setup SSH key
+        run: |
+          mkdir -p ~/.ssh
+          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
+          chmod 600 ~/.ssh/id_rsa
+          # Convertir la clé en PEM si nécessaire (si la clé est au format RSA classique)
+          if ! openssl rsa -in ~/.ssh/id_rsa -out ~/.ssh/id_rsa.pem; then
+            echo "Failed to convert key to PEM format"
+            exit 1
+          fi
+          # Ajouter l'hôte à la liste des known_hosts pour éviter les avertissements
+          ssh-keyscan -H ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts
 
       # Déployer la branche 'main' sur le prod
       - name: Deploy on main branch
